version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies and run tests (you can add your own tests)
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

      # Deploy to AWS using Terraform (replace with your own Terraform commands)
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Deploy to AWS
          command: |
            terraform init
            terraform apply -auto-approve
