version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"  # Expose the MySQL port
    volumes:
      - ./sql-scripts/create_database.sql:/docker-entrypoint-initdb.d/1.sql
  backend:
    build:
      context: .././back-end  # Specify the path to your backend Dockerfile and application code
    ports:
      - "8000:8000"  # Expose the backend port
    depends_on:
      - db

  frontend:
    build:
      context: .././front-end  # Specify the path to your frontend Dockerfile and application code
    ports:
      - "3000:3000"  # Expose the frontend port
    depends_on:
      - backend
